"""Pydantic schemas for API request/response."""
from indexer_api.schemas.auth import (
    APIKeyCreate,
    APIKeyCreated,
    APIKeyResponse,
    OrganizationCreate,
    OrganizationResponse,
    OrganizationUpdate,
    OrganizationUsage,
    RefreshTokenRequest,
    Token,
    TokenPayload,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
    UserWithOrganization,
)
from indexer_api.schemas.base import (
    BaseSchema,
    ErrorResponse,
    HealthResponse,
    PaginatedResponse,
    SuccessResponse,
    TimestampMixin,
)
from indexer_api.schemas.index import (
    DuplicateFilesResponse,
    FileIndexCreate,
    FileIndexResponse,
    FileIndexStats,
    FileIndexUpdate,
    IndexedFileResponse,
    IndexedFileSearch,
    IndexJobCreate,
    IndexJobProgress,
    IndexJobResponse,
    SearchResponse,
    SearchResult,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampMixin",
    "PaginatedResponse",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",
    # Auth
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserWithOrganization",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationUsage",
    "APIKeyCreate",
    "APIKeyCreated",
    "APIKeyResponse",
    # Index
    "FileIndexCreate",
    "FileIndexUpdate",
    "FileIndexResponse",
    "FileIndexStats",
    "IndexedFileResponse",
    "IndexedFileSearch",
    "DuplicateFilesResponse",
    "IndexJobCreate",
    "IndexJobResponse",
    "IndexJobProgress",
    "SearchResult",
    "SearchResponse",
]
